#!/usr/bin/env node
/**
 * Sitemap Comparison Script
 * 
 * Compares the original sitemap (public/sitemap.xml) with the generated sitemap
 * from @astrojs/sitemap to verify URL coverage.
 * 
 * Requirements: 5.3, 8.5
 */

import { readFile, stat } from 'fs/promises';

const ORIGINAL_SITEMAP = 'public/sitemap.xml';
const GENERATED_SITEMAP_INDEX = 'dist/sitemap-index.xml';
const GENERATED_SITEMAP = 'dist/sitemap-0.xml';
const BASELINE_JSON = 'scripts/snapshots/sitemap-baseline.json';

/**
 * Parse sitemap XML and extract URLs
 */
function parseSitemap(xml) {
  const urls = [];
  // Handle both formatted and minified XML
  const urlRegex = /<url>[\s\S]*?<\/url>/g;
  const locRegex = /<loc>([^<]*)<\/loc>/;
  
  let match;
  while ((match = urlRegex.exec(xml)) !== null) {
    const urlBlock = match[0];
    const locMatch = urlBlock.match(locRegex);
    if (locMatch) {
      urls.push(locMatch[1]);
    }
  }
  
  // If no <url> tags found, try to extract <loc> directly (for minified format)
  if (urls.length === 0) {
    const directLocRegex = /<loc>([^<]*)<\/loc>/g;
    while ((match = directLocRegex.exec(xml)) !== null) {
      urls.push(match[1]);
    }
  }
  
  return urls;
}

/**
 * Normalize URL for comparison (remove trailing slash differences)
 */
function normalizeUrl(url) {
  // Ensure consistent trailing slash
  return url.endsWith('/') ? url : url + '/';
}

async function main() {
  console.log('🗺️  Sitemap Comparison Script');
  console.log('='.repeat(60));
  
  // Read original sitemap
  let originalUrls = [];
  try {
    const originalContent = await readFile(ORIGINAL_SITEMAP, 'utf-8');
    originalUrls = parseSitemap(originalContent);
    console.log(`📂 Original sitemap (${ORIGINAL_SITEMAP}): ${originalUrls.length} URLs`);
  } catch (e) {
    console.error(`❌ Could not read original sitemap: ${e.message}`);
    process.exit(1);
  }
  
  // Read generated sitemap
  let generatedUrls = [];
  try {
    // Check if sitemap-0.xml exists (generated by @astrojs/sitemap)
    await stat(GENERATED_SITEMAP);
    const generatedContent = await readFile(GENERATED_SITEMAP, 'utf-8');
    generatedUrls = parseSitemap(generatedContent);
    console.log(`📂 Generated sitemap (${GENERATED_SITEMAP}): ${generatedUrls.length} URLs`);
  } catch (e) {
    console.error(`❌ Could not read generated sitemap: ${e.message}`);
    console.error('   Run "npm run build" first to generate the sitemap.');
    process.exit(1);
  }
  
  // Normalize URLs for comparison
  const originalSet = new Set(originalUrls.map(normalizeUrl));
  const generatedSet = new Set(generatedUrls.map(normalizeUrl));
  
  // Find differences
  const missingFromGenerated = [...originalSet].filter(url => !generatedSet.has(url));
  const newInGenerated = [...generatedSet].filter(url => !originalSet.has(url));
  const common = [...originalSet].filter(url => generatedSet.has(url));
  
  console.log('\n' + '='.repeat(60));
  console.log('📊 Comparison Results:');
  console.log(`   Common URLs: ${common.length}`);
  console.log(`   Missing from generated: ${missingFromGenerated.length}`);
  console.log(`   New in generated: ${newInGenerated.length}`);
  
  // Show missing URLs (these are critical - they were in original but not generated)
  if (missingFromGenerated.length > 0) {
    console.log('\n❌ URLs in original but MISSING from generated sitemap:');
    missingFromGenerated.slice(0, 20).forEach(url => console.log(`   - ${url}`));
    if (missingFromGenerated.length > 20) {
      console.log(`   ... and ${missingFromGenerated.length - 20} more`);
    }
  }
  
  // Show new URLs (these are additions - may be expected)
  if (newInGenerated.length > 0) {
    console.log('\n⚠️  URLs in generated but NOT in original sitemap:');
    
    // Categorize new URLs
    const categoryUrls = newInGenerated.filter(url => url.includes('/c/'));
    const otherNewUrls = newInGenerated.filter(url => !url.includes('/c/'));
    
    if (categoryUrls.length > 0) {
      console.log(`   Category pages (/c/*): ${categoryUrls.length}`);
    }
    
    if (otherNewUrls.length > 0) {
      console.log('   Other new pages:');
      otherNewUrls.slice(0, 15).forEach(url => console.log(`   + ${url}`));
      if (otherNewUrls.length > 15) {
        console.log(`   ... and ${otherNewUrls.length - 15} more`);
      }
    }
  }
  
  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('📋 Summary:');
  
  const coveragePercent = ((common.length / originalSet.size) * 100).toFixed(1);
  console.log(`   Original URL coverage: ${coveragePercent}% (${common.length}/${originalSet.size})`);
  
  if (missingFromGenerated.length === 0) {
    console.log('✅ All original sitemap URLs are present in generated sitemap!');
    console.log('   (Generated sitemap may include additional pages like category pages)');
  } else {
    console.log(`❌ ${missingFromGenerated.length} URLs from original sitemap are missing!`);
    console.log('   This may affect SEO - review the missing URLs above.');
  }
  
  // Note about format differences
  console.log('\n📝 Note: The generated sitemap uses a different format:');
  console.log('   - Original: includes lastmod, changefreq, priority');
  console.log('   - Generated: only includes loc (URL)');
  console.log('   This is expected behavior from @astrojs/sitemap.');
  console.log('   The original sitemap.xml in public/ is still copied to dist/');
  console.log('   and can be used as the primary sitemap if needed.');
}

main().catch(console.error);
